[package]
name = "key-store-lite"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
rayon = "1.10.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = "1.40.0"

[[bin]]
name = "testing-server"
path = "src/bin/main.rs"
